//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.ccdb.session.view.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "createNewCustomer", namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createNewCustomer", namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", propOrder = {
    "arg0",
    "arg1",
    "arg2"
})
public class CreateNewCustomer {

    @XmlElement(name = "arg0", namespace = "")
    private com.ibm.websphere.svt.gs.ccdb.entities.CcAuthInfo arg0;
    @XmlElement(name = "arg1", namespace = "")
    private com.ibm.websphere.svt.gs.ccdb.entities.CcInfo arg1;
    @XmlElement(name = "arg2", namespace = "")
    private com.ibm.websphere.svt.gs.ccdb.entities.CcOwnerInfo arg2;

    /**
     * 
     * @return
     *     returns CcAuthInfo
     */
    public com.ibm.websphere.svt.gs.ccdb.entities.CcAuthInfo getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(com.ibm.websphere.svt.gs.ccdb.entities.CcAuthInfo arg0) {
        this.arg0 = arg0;
    }

    /**
     * 
     * @return
     *     returns CcInfo
     */
    public com.ibm.websphere.svt.gs.ccdb.entities.CcInfo getArg1() {
        return this.arg1;
    }

    /**
     * 
     * @param arg1
     *     the value for the arg1 property
     */
    public void setArg1(com.ibm.websphere.svt.gs.ccdb.entities.CcInfo arg1) {
        this.arg1 = arg1;
    }

    /**
     * 
     * @return
     *     returns CcOwnerInfo
     */
    public com.ibm.websphere.svt.gs.ccdb.entities.CcOwnerInfo getArg2() {
        return this.arg2;
    }

    /**
     * 
     * @param arg2
     *     the value for the arg2 property
     */
    public void setArg2(com.ibm.websphere.svt.gs.ccdb.entities.CcOwnerInfo arg2) {
        this.arg2 = arg2;
    }

}
