//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.ccdb.session.view.jaxws;

import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "showHistoryInfoResponse", namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "showHistoryInfoResponse", namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/")
public class ShowHistoryInfoResponse {

    @XmlElement(name = "return", namespace = "")
    private List<com.ibm.websphere.svt.gs.ccdb.entities.CcHistory> _return;

    /**
     * 
     * @return
     *     returns List<CcHistory>
     */
    public List<com.ibm.websphere.svt.gs.ccdb.entities.CcHistory> getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(List<com.ibm.websphere.svt.gs.ccdb.entities.CcHistory> _return) {
        this._return = _return;
    }

}
