//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.wsbankdb.session.view.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "getTransactionHistoryResponse", namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getTransactionHistoryResponse", namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/")
public class GetTransactionHistoryResponse {

    @XmlElement(name = "return", namespace = "")
    private com.ibm.websphere.svt.gs.wrapper.TransactionHistoryWrapper _return;

    /**
     * 
     * @return
     *     returns TransactionHistoryWrapper
     */
    public com.ibm.websphere.svt.gs.wrapper.TransactionHistoryWrapper getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(com.ibm.websphere.svt.gs.wrapper.TransactionHistoryWrapper _return) {
        this._return = _return;
    }

}
