//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.gsdb.session.view.jaxws;

import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "listCategoriesResponse", namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listCategoriesResponse", namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/")
public class ListCategoriesResponse {

    @XmlElement(name = "return", namespace = "")
    private Vector<com.ibm.websphere.svt.gs.wrapper.CategoryWrapper> _return;

    /**
     * 
     * @return
     *     returns Vector<CategoryWrapper>
     */
    public Vector<com.ibm.websphere.svt.gs.wrapper.CategoryWrapper> getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(Vector<com.ibm.websphere.svt.gs.wrapper.CategoryWrapper> _return) {
        this._return = _return;
    }

}
