<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
  	<groupId>com.ibm.ws.svt.gs.twas90.liberty.ease4j.garagesale-ee7</groupId>
  	<artifactId>garageSale-ee7</artifactId>
  	<version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>GSjsf20LibertyWeb</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>
  <build>
  <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <configuration>
			<outputFileNameMapping>@{artifactId}@.@{extension}@</outputFileNameMapping>
        </configuration>
      </plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<configuration>
					<skip>${app.deploy.skip}</skip>
				</configuration>
			</plugin>
    </plugins>
  </build>
  <dependencies>
  	<dependency>
	  	<groupId>com.ibm.ws.svt.gs.twas90.liberty.ease4j.garagesale-ee7</groupId>
  		<artifactId>GarageSaleEJB</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  		<type>ejb</type>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.apache.myfaces.core</groupId>
  		<artifactId>myfaces-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.el</groupId>
  		<artifactId>javax.el-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.enterprise</groupId>
  		<artifactId>cdi-api</artifactId>
  		<scope>provided</scope>
  	</dependency>	
  	<dependency>
  		<groupId>javax.interceptor</groupId>
  		<artifactId>javax.interceptor-api</artifactId>
  		<scope>provided</scope>
  	</dependency>	
  	<dependency>
	  	<groupId>com.ibm.ws.svt.gs.twas90.liberty.ease4j.garagesale-ee7</groupId>
  		<artifactId>GarageSaleWSClient</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.apache.wink</groupId>
  		<artifactId>wink-client-apache-httpclient</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.enterprise.concurrent</groupId>
  		<artifactId>javax.enterprise.concurrent-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.faces</groupId>
  		<artifactId>javax.faces-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.websocket</groupId>
  		<artifactId>javax.websocket-client-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.servlet</groupId>
  		<artifactId>javax.servlet-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
	  	<groupId>com.ibm.ws.svt.gs.twas90.liberty.ease4j.garagesale-ee7</groupId>
  		<artifactId>ProdReviewTaxShipRateEJB</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  		<type>ejb</type>
  	</dependency>
  	<dependency>
  		<groupId>javax.websocket</groupId>
  		<artifactId>javax.websocket-all</artifactId>
  		<type>pom</type>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.validation</groupId>
  		<artifactId>validation-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>com.ibm.websphere.appserver.api</groupId>
  		<artifactId>com.ibm.websphere.appserver.api.json</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.ws.rs</groupId>
  		<artifactId>javax.ws.rs-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>org.eclipse.jetty.websocket</groupId>
  		<artifactId>javax-websocket-server-impl</artifactId>
  		<scope>provided</scope>
  	</dependency>
  	<dependency>
  		<groupId>javax.ejb</groupId>
  		<artifactId>javax.ejb-api</artifactId>
  		<scope>provided</scope>
  	</dependency>
<!--  
  	<dependency>
     <groupId>cdi2.0</groupId>
     <artifactId>cdi2.0</artifactId>
     <version>2.0</version>
     <scope>system</scope>
     <systemPath>C:\Liberty\wlp\dev\api\spec\com.ibm.websphere.javaee.cdi.2.0_1.0.19.jar</systemPath>
    </dependency> 
-->    
<!--  
    <dependency>
     <groupId>interceptor1.2</groupId>
     <artifactId>interceptor1.2</artifactId>
     <version>1.2</version>
     <scope>system</scope>
     <systemPath>C:\Liberty\wlp\dev\api\spec\com.ibm.websphere.javaee.interceptor.1.2_1.0.19.jar</systemPath>
    </dependency>
-->     
  </dependencies>  
</project>