//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.wsbankdb.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "GarageSaleBankManagerLocal", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GarageSaleBankManagerLocal {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createAccountsForGS", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.CreateAccountsForGS")
    @ResponseWrapper(localName = "createAccountsForGSResponse", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.CreateAccountsForGSResponse")
    @Action(input = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/createAccountsForGSRequest", output = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/createAccountsForGSResponse")
    public void createAccountsForGS(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doTransaction", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.DoTransaction")
    @ResponseWrapper(localName = "doTransactionResponse", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.DoTransactionResponse")
    @Action(input = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/doTransactionRequest", output = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/doTransactionResponse")
    public boolean doTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        boolean arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.FloatArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountBalances", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.GetAccountBalances")
    @ResponseWrapper(localName = "getAccountBalancesResponse", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.GetAccountBalancesResponse")
    @Action(input = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/getAccountBalancesRequest", output = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/getAccountBalancesResponse")
    public List<FloatArray> getAccountBalances(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.TransactionHistoryWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransactionHistory", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.GetTransactionHistory")
    @ResponseWrapper(localName = "getTransactionHistoryResponse", targetNamespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.wsbankdb.jaxws.client.GetTransactionHistoryResponse")
    @Action(input = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/getTransactionHistoryRequest", output = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/GarageSaleBankManagerLocal/getTransactionHistoryResponse")
    public TransactionHistoryWrapper getTransactionHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
