//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.wsbankdb.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "GarageSaleBankManagerService", targetNamespace = "http://session.wsbankdb.gs.svt.websphere.ibm.com/", wsdlLocation = "META-INF/wsdl/GarageSaleBankManagerService.wsdl")
public class GarageSaleBankManagerService
    extends Service
{

    private final static URL GARAGESALEBANKMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException GARAGESALEBANKMANAGERSERVICE_EXCEPTION;
    private final static QName GARAGESALEBANKMANAGERSERVICE_QNAME = new QName("http://session.wsbankdb.gs.svt.websphere.ibm.com/", "GarageSaleBankManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("META-INF/wsdl/GarageSaleBankManagerService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GARAGESALEBANKMANAGERSERVICE_WSDL_LOCATION = url;
        GARAGESALEBANKMANAGERSERVICE_EXCEPTION = e;
    }

    public GarageSaleBankManagerService() {
        super(__getWsdlLocation(), GARAGESALEBANKMANAGERSERVICE_QNAME);
    }

    public GarageSaleBankManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GARAGESALEBANKMANAGERSERVICE_QNAME, features);
    }

    public GarageSaleBankManagerService(URL wsdlLocation) {
        super(wsdlLocation, GARAGESALEBANKMANAGERSERVICE_QNAME);
    }

    public GarageSaleBankManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GARAGESALEBANKMANAGERSERVICE_QNAME, features);
    }

    public GarageSaleBankManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GarageSaleBankManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GarageSaleBankManagerLocal
     */
    @WebEndpoint(name = "GarageSaleBankManagerPort")
    public GarageSaleBankManagerLocal getGarageSaleBankManagerPort() {
        return super.getPort(new QName("http://session.wsbankdb.gs.svt.websphere.ibm.com/", "GarageSaleBankManagerPort"), GarageSaleBankManagerLocal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GarageSaleBankManagerLocal
     */
    @WebEndpoint(name = "GarageSaleBankManagerPort")
    public GarageSaleBankManagerLocal getGarageSaleBankManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://session.wsbankdb.gs.svt.websphere.ibm.com/", "GarageSaleBankManagerPort"), GarageSaleBankManagerLocal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GARAGESALEBANKMANAGERSERVICE_EXCEPTION!= null) {
            throw GARAGESALEBANKMANAGERSERVICE_EXCEPTION;
        }
        return GARAGESALEBANKMANAGERSERVICE_WSDL_LOCATION;
    }

}
