//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.wsbankdb.jaxws.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.websphere.svt.gs.wsbankdb.jaxws.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateAccountsForGSResponse_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "createAccountsForGSResponse");
    private final static QName _GetTransactionHistory_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "getTransactionHistory");
    private final static QName _GetTransactionHistoryResponse_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "getTransactionHistoryResponse");
    private final static QName _DoTransaction_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "doTransaction");
    private final static QName _DoTransactionResponse_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "doTransactionResponse");
    private final static QName _GetAccountBalancesResponse_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "getAccountBalancesResponse");
    private final static QName _CreateAccountsForGS_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "createAccountsForGS");
    private final static QName _GetAccountBalances_QNAME = new QName("http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", "getAccountBalances");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.websphere.svt.gs.wsbankdb.jaxws.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FloatArray }
     * 
     */
    public FloatArray createFloatArray() {
        return new FloatArray();
    }

    /**
     * Create an instance of {@link DoTransactionResponse }
     * 
     */
    public DoTransactionResponse createDoTransactionResponse() {
        return new DoTransactionResponse();
    }

    /**
     * Create an instance of {@link GetAccountBalances }
     * 
     */
    public GetAccountBalances createGetAccountBalances() {
        return new GetAccountBalances();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryResponse }
     * 
     */
    public GetTransactionHistoryResponse createGetTransactionHistoryResponse() {
        return new GetTransactionHistoryResponse();
    }

    /**
     * Create an instance of {@link GetTransactionHistory }
     * 
     */
    public GetTransactionHistory createGetTransactionHistory() {
        return new GetTransactionHistory();
    }

    /**
     * Create an instance of {@link CreateAccountsForGSResponse }
     * 
     */
    public CreateAccountsForGSResponse createCreateAccountsForGSResponse() {
        return new CreateAccountsForGSResponse();
    }

    /**
     * Create an instance of {@link GetAccountBalancesResponse }
     * 
     */
    public GetAccountBalancesResponse createGetAccountBalancesResponse() {
        return new GetAccountBalancesResponse();
    }

    /**
     * Create an instance of {@link DoTransaction }
     * 
     */
    public DoTransaction createDoTransaction() {
        return new DoTransaction();
    }

    /**
     * Create an instance of {@link CreateAccountsForGS }
     * 
     */
    public CreateAccountsForGS createCreateAccountsForGS() {
        return new CreateAccountsForGS();
    }

    /**
     * Create an instance of {@link TransactionHistoryWrapper }
     * 
     */
    public TransactionHistoryWrapper createTransactionHistoryWrapper() {
        return new TransactionHistoryWrapper();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountsForGSResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "createAccountsForGSResponse")
    public JAXBElement<CreateAccountsForGSResponse> createCreateAccountsForGSResponse(CreateAccountsForGSResponse value) {
        return new JAXBElement<CreateAccountsForGSResponse>(_CreateAccountsForGSResponse_QNAME, CreateAccountsForGSResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "getTransactionHistory")
    public JAXBElement<GetTransactionHistory> createGetTransactionHistory(GetTransactionHistory value) {
        return new JAXBElement<GetTransactionHistory>(_GetTransactionHistory_QNAME, GetTransactionHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransactionHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "getTransactionHistoryResponse")
    public JAXBElement<GetTransactionHistoryResponse> createGetTransactionHistoryResponse(GetTransactionHistoryResponse value) {
        return new JAXBElement<GetTransactionHistoryResponse>(_GetTransactionHistoryResponse_QNAME, GetTransactionHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoTransaction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "doTransaction")
    public JAXBElement<DoTransaction> createDoTransaction(DoTransaction value) {
        return new JAXBElement<DoTransaction>(_DoTransaction_QNAME, DoTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoTransactionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "doTransactionResponse")
    public JAXBElement<DoTransactionResponse> createDoTransactionResponse(DoTransactionResponse value) {
        return new JAXBElement<DoTransactionResponse>(_DoTransactionResponse_QNAME, DoTransactionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountBalancesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "getAccountBalancesResponse")
    public JAXBElement<GetAccountBalancesResponse> createGetAccountBalancesResponse(GetAccountBalancesResponse value) {
        return new JAXBElement<GetAccountBalancesResponse>(_GetAccountBalancesResponse_QNAME, GetAccountBalancesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountsForGS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "createAccountsForGS")
    public JAXBElement<CreateAccountsForGS> createCreateAccountsForGS(CreateAccountsForGS value) {
        return new JAXBElement<CreateAccountsForGS>(_CreateAccountsForGS_QNAME, CreateAccountsForGS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountBalances }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.wsbankdb.gs.svt.websphere.ibm.com/", name = "getAccountBalances")
    public JAXBElement<GetAccountBalances> createGetAccountBalances(GetAccountBalances value) {
        return new JAXBElement<GetAccountBalances>(_GetAccountBalances_QNAME, GetAccountBalances.class, null, value);
    }

}
