//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.websphere.svt.gs.wrapper;

import java.io.Serializable;


/**
 * <p>Java class for CategoryWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CategoryWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categoryDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="categoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numItemsInCategory" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryWrapper", namespace = "http://wrapper.gs.svt.websphere.ibm.com", propOrder = {
    "categoryDescription",
    "categoryName",
    "numItemsInCategory"
})*/
public class CategoryWrapper implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 6868897976039360487L;
	protected String categoryDescription;
    protected String categoryName;
    protected int numItemsInCategory;

    /**
     * Gets the value of the categoryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryDescription() {
        return categoryDescription;
    }

    /**
     * Sets the value of the categoryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryDescription(String value) {
        this.categoryDescription = value;
    }

    /**
     * Gets the value of the categoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * Sets the value of the categoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryName(String value) {
        this.categoryName = value;
    }

    /**
     * Gets the value of the numItemsInCategory property.
     * 
     */
    public int getNumItemsInCategory() {
        return numItemsInCategory;
    }

    /**
     * Sets the value of the numItemsInCategory property.
     * 
     */
    public void setNumItemsInCategory(int value) {
        this.numItemsInCategory = value;
    }

}
