//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.websphere.svt.gs.wrapper;

import java.io.Serializable;


/**
 * <p>Java class for CustomerWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custPwd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numInvoicesCompleted" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numInvoicesCreated" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerWrapper", namespace = "http://wrapper.gs.svt.websphere.ibm.com", propOrder = {
    "custID",
    "custName",
    "custPwd",
    "numInvoicesCompleted",
    "numInvoicesCreated"
})*/
public class CustomerWrapper implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -6732430904991304948L;
	/**
	 * 
	 */
	protected String custID;
    protected String custName;
    protected String custPwd;
    protected int numInvoicesCompleted;
    protected int numInvoicesCreated;

    /**
     * Gets the value of the custID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustID() {
        return custID;
    }

    /**
     * Sets the value of the custID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustID(String value) {
        this.custID = value;
    }

    /**
     * Gets the value of the custName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustName() {
        return custName;
    }

    /**
     * Sets the value of the custName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustName(String value) {
        this.custName = value;
    }

    /**
     * Gets the value of the custPwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustPwd() {
        return custPwd;
    }

    /**
     * Sets the value of the custPwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustPwd(String value) {
        this.custPwd = value;
    }

    /**
     * Gets the value of the numInvoicesCompleted property.
     * 
     */
    public int getNumInvoicesCompleted() {
        return numInvoicesCompleted;
    }

    /**
     * Sets the value of the numInvoicesCompleted property.
     * 
     */
    public void setNumInvoicesCompleted(int value) {
        this.numInvoicesCompleted = value;
    }

    /**
     * Gets the value of the numInvoicesCreated property.
     * 
     */
    public int getNumInvoicesCreated() {
        return numInvoicesCreated;
    }

    /**
     * Sets the value of the numInvoicesCreated property.
     * 
     */
    public void setNumInvoicesCreated(int value) {
        this.numInvoicesCreated = value;
    }

}
