//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://wrapper.gs.svt.websphere.ibm.com")
package com.ibm.websphere.svt.gs.wrapper;
