//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.ccdb.jaxws.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.websphere.svt.gs.ccdb.jaxws.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RemoveCCInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "removeCCInfoResponse");
    private final static QName _GenTransID_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "genTransID");
    private final static QName _CreateCCInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCInfo");
    private final static QName _ResetCCDB_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "resetCCDB");
    private final static QName _DoCredit_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "doCredit");
    private final static QName _RemoveCCAuthInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "removeCCAuthInfo");
    private final static QName _CreateAccountForGSResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createAccountForGSResponse");
    private final static QName _GenCCNumResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "genCCNumResponse");
    private final static QName _CreateCCOwnerInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCOwnerInfoResponse");
    private final static QName _CreateCCAuthInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCAuthInfoResponse");
    private final static QName _ClearCCDBResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "clearCCDBResponse");
    private final static QName _UpdateCCInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "updateCCInfo");
    private final static QName _DoCreditResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "doCreditResponse");
    private final static QName _UpdateCCAuthInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "updateCCAuthInfo");
    private final static QName _UpdateCCOwnerInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "updateCCOwnerInfoResponse");
    private final static QName _ClearCCDB_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "clearCCDB");
    private final static QName _GenTransIDResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "genTransIDResponse");
    private final static QName _DoDebit_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "doDebit");
    private final static QName _DoDebitResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "doDebitResponse");
    private final static QName _ShowHistoryInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "showHistoryInfoResponse");
    private final static QName _GenCCNum_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "genCCNum");
    private final static QName _GetCCInfoWrapperResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "getCCInfoWrapperResponse");
    private final static QName _ResetCCDBResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "resetCCDBResponse");
    private final static QName _ValidateCard_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "validateCard");
    private final static QName _ShowHistoryInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "showHistoryInfo");
    private final static QName _ValidateCardResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "validateCardResponse");
    private final static QName _UpdateCCInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "updateCCInfoResponse");
    private final static QName _RemoveCCAuthInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "removeCCAuthInfoResponse");
    private final static QName _RemoveCCInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "removeCCInfo");
    private final static QName _CreateCCAuthInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCAuthInfo");
    private final static QName _RemoveCCOwner_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "removeCCOwner");
    private final static QName _RemoveCCOwnerResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "removeCCOwnerResponse");
    private final static QName _CreateCCOwnerInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCOwnerInfo");
    private final static QName _CreateCCInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCInfoResponse");
    private final static QName _UpdateCCOwnerInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "updateCCOwnerInfo");
    private final static QName _CreateNewCustomer_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createNewCustomer");
    private final static QName _CreateNewCustomerResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createNewCustomerResponse");
    private final static QName _GetCCInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "getCCInfoResponse");
    private final static QName _GetCCInfoWrapper_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "getCCInfoWrapper");
    private final static QName _GetCCInfo_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "getCCInfo");
    private final static QName _UpdateCCAuthInfoResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "updateCCAuthInfoResponse");
    private final static QName _CreateCCHistoryResponse_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCHistoryResponse");
    private final static QName _CreateCCHistory_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createCCHistory");
    private final static QName _CreateAccountForGS_QNAME = new QName("http://view.session.ccdb.gs.svt.websphere.ibm.com/", "createAccountForGS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.websphere.svt.gs.ccdb.jaxws.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateCCInfo }
     * 
     */
    public UpdateCCInfo createUpdateCCInfo() {
        return new UpdateCCInfo();
    }

    /**
     * Create an instance of {@link CreateCCHistoryResponse }
     * 
     */
    public CreateCCHistoryResponse createCreateCCHistoryResponse() {
        return new CreateCCHistoryResponse();
    }

    /**
     * Create an instance of {@link CreateNewCustomerResponse }
     * 
     */
    public CreateNewCustomerResponse createCreateNewCustomerResponse() {
        return new CreateNewCustomerResponse();
    }

    /**
     * Create an instance of {@link ClearCCDB }
     * 
     */
    public ClearCCDB createClearCCDB() {
        return new ClearCCDB();
    }

    /**
     * Create an instance of {@link CreateCCOwnerInfo }
     * 
     */
    public CreateCCOwnerInfo createCreateCCOwnerInfo() {
        return new CreateCCOwnerInfo();
    }

    /**
     * Create an instance of {@link ValidateCard }
     * 
     */
    public ValidateCard createValidateCard() {
        return new ValidateCard();
    }

    /**
     * Create an instance of {@link GenCCNum }
     * 
     */
    public GenCCNum createGenCCNum() {
        return new GenCCNum();
    }

    /**
     * Create an instance of {@link RemoveCCAuthInfo }
     * 
     */
    public RemoveCCAuthInfo createRemoveCCAuthInfo() {
        return new RemoveCCAuthInfo();
    }

    /**
     * Create an instance of {@link CreateCCAuthInfo }
     * 
     */
    public CreateCCAuthInfo createCreateCCAuthInfo() {
        return new CreateCCAuthInfo();
    }

    /**
     * Create an instance of {@link ClearCCDBResponse }
     * 
     */
    public ClearCCDBResponse createClearCCDBResponse() {
        return new ClearCCDBResponse();
    }

    /**
     * Create an instance of {@link UpdateCCOwnerInfoResponse }
     * 
     */
    public UpdateCCOwnerInfoResponse createUpdateCCOwnerInfoResponse() {
        return new UpdateCCOwnerInfoResponse();
    }

    /**
     * Create an instance of {@link RemoveCCInfoResponse }
     * 
     */
    public RemoveCCInfoResponse createRemoveCCInfoResponse() {
        return new RemoveCCInfoResponse();
    }

    /**
     * Create an instance of {@link GenTransID }
     * 
     */
    public GenTransID createGenTransID() {
        return new GenTransID();
    }

    /**
     * Create an instance of {@link GenTransIDResponse }
     * 
     */
    public GenTransIDResponse createGenTransIDResponse() {
        return new GenTransIDResponse();
    }

    /**
     * Create an instance of {@link UpdateCCAuthInfoResponse }
     * 
     */
    public UpdateCCAuthInfoResponse createUpdateCCAuthInfoResponse() {
        return new UpdateCCAuthInfoResponse();
    }

    /**
     * Create an instance of {@link CreateCCInfoResponse }
     * 
     */
    public CreateCCInfoResponse createCreateCCInfoResponse() {
        return new CreateCCInfoResponse();
    }

    /**
     * Create an instance of {@link ResetCCDB }
     * 
     */
    public ResetCCDB createResetCCDB() {
        return new ResetCCDB();
    }

    /**
     * Create an instance of {@link DoCredit }
     * 
     */
    public DoCredit createDoCredit() {
        return new DoCredit();
    }

    /**
     * Create an instance of {@link RemoveCCAuthInfoResponse }
     * 
     */
    public RemoveCCAuthInfoResponse createRemoveCCAuthInfoResponse() {
        return new RemoveCCAuthInfoResponse();
    }

    /**
     * Create an instance of {@link GetCCInfoWrapper }
     * 
     */
    public GetCCInfoWrapper createGetCCInfoWrapper() {
        return new GetCCInfoWrapper();
    }

    /**
     * Create an instance of {@link CreateAccountForGS }
     * 
     */
    public CreateAccountForGS createCreateAccountForGS() {
        return new CreateAccountForGS();
    }

    /**
     * Create an instance of {@link RemoveCCOwnerResponse }
     * 
     */
    public RemoveCCOwnerResponse createRemoveCCOwnerResponse() {
        return new RemoveCCOwnerResponse();
    }

    /**
     * Create an instance of {@link DoCreditResponse }
     * 
     */
    public DoCreditResponse createDoCreditResponse() {
        return new DoCreditResponse();
    }

    /**
     * Create an instance of {@link GetCCInfoResponse }
     * 
     */
    public GetCCInfoResponse createGetCCInfoResponse() {
        return new GetCCInfoResponse();
    }

    /**
     * Create an instance of {@link ShowHistoryInfo }
     * 
     */
    public ShowHistoryInfo createShowHistoryInfo() {
        return new ShowHistoryInfo();
    }

    /**
     * Create an instance of {@link RemoveCCInfo }
     * 
     */
    public RemoveCCInfo createRemoveCCInfo() {
        return new RemoveCCInfo();
    }

    /**
     * Create an instance of {@link UpdateCCInfoResponse }
     * 
     */
    public UpdateCCInfoResponse createUpdateCCInfoResponse() {
        return new UpdateCCInfoResponse();
    }

    /**
     * Create an instance of {@link ShowHistoryInfoResponse }
     * 
     */
    public ShowHistoryInfoResponse createShowHistoryInfoResponse() {
        return new ShowHistoryInfoResponse();
    }

    /**
     * Create an instance of {@link GetCCInfoWrapperResponse }
     * 
     */
    public GetCCInfoWrapperResponse createGetCCInfoWrapperResponse() {
        return new GetCCInfoWrapperResponse();
    }

    /**
     * Create an instance of {@link GetCCInfo }
     * 
     */
    public GetCCInfo createGetCCInfo() {
        return new GetCCInfo();
    }

    /**
     * Create an instance of {@link CreateCCOwnerInfoResponse }
     * 
     */
    public CreateCCOwnerInfoResponse createCreateCCOwnerInfoResponse() {
        return new CreateCCOwnerInfoResponse();
    }

    /**
     * Create an instance of {@link CreateCCHistory }
     * 
     */
    public CreateCCHistory createCreateCCHistory() {
        return new CreateCCHistory();
    }

    /**
     * Create an instance of {@link CreateNewCustomer }
     * 
     */
    public CreateNewCustomer createCreateNewCustomer() {
        return new CreateNewCustomer();
    }

    /**
     * Create an instance of {@link ValidateCardResponse }
     * 
     */
    public ValidateCardResponse createValidateCardResponse() {
        return new ValidateCardResponse();
    }

    /**
     * Create an instance of {@link ResetCCDBResponse }
     * 
     */
    public ResetCCDBResponse createResetCCDBResponse() {
        return new ResetCCDBResponse();
    }

    /**
     * Create an instance of {@link RemoveCCOwner }
     * 
     */
    public RemoveCCOwner createRemoveCCOwner() {
        return new RemoveCCOwner();
    }

    /**
     * Create an instance of {@link DoDebit }
     * 
     */
    public DoDebit createDoDebit() {
        return new DoDebit();
    }

    /**
     * Create an instance of {@link GenCCNumResponse }
     * 
     */
    public GenCCNumResponse createGenCCNumResponse() {
        return new GenCCNumResponse();
    }

    /**
     * Create an instance of {@link CreateCCAuthInfoResponse }
     * 
     */
    public CreateCCAuthInfoResponse createCreateCCAuthInfoResponse() {
        return new CreateCCAuthInfoResponse();
    }

    /**
     * Create an instance of {@link CreateAccountForGSResponse }
     * 
     */
    public CreateAccountForGSResponse createCreateAccountForGSResponse() {
        return new CreateAccountForGSResponse();
    }

    /**
     * Create an instance of {@link UpdateCCAuthInfo }
     * 
     */
    public UpdateCCAuthInfo createUpdateCCAuthInfo() {
        return new UpdateCCAuthInfo();
    }

    /**
     * Create an instance of {@link UpdateCCOwnerInfo }
     * 
     */
    public UpdateCCOwnerInfo createUpdateCCOwnerInfo() {
        return new UpdateCCOwnerInfo();
    }

    /**
     * Create an instance of {@link DoDebitResponse }
     * 
     */
    public DoDebitResponse createDoDebitResponse() {
        return new DoDebitResponse();
    }

    /**
     * Create an instance of {@link CreateCCInfo }
     * 
     */
    public CreateCCInfo createCreateCCInfo() {
        return new CreateCCInfo();
    }

    /**
     * Create an instance of {@link CcHistory }
     * 
     */
    public CcHistory createCcHistory() {
        return new CcHistory();
    }

    /**
     * Create an instance of {@link CcAuthInfo }
     * 
     */
    public CcAuthInfo createCcAuthInfo() {
        return new CcAuthInfo();
    }

    /**
     * Create an instance of {@link CcHistoryPK }
     * 
     */
    public CcHistoryPK createCcHistoryPK() {
        return new CcHistoryPK();
    }

    /**
     * Create an instance of {@link CcInfo }
     * 
     */
    public CcInfo createCcInfo() {
        return new CcInfo();
    }

    /**
     * Create an instance of {@link CcOwnerInfo }
     * 
     */
    public CcOwnerInfo createCcOwnerInfo() {
        return new CcOwnerInfo();
    }

    /**
     * Create an instance of {@link CCInfoWrapper }
     * 
     */
    public CCInfoWrapper createCCInfoWrapper() {
        return new CCInfoWrapper();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveCCInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "removeCCInfoResponse")
    public JAXBElement<RemoveCCInfoResponse> createRemoveCCInfoResponse(RemoveCCInfoResponse value) {
        return new JAXBElement<RemoveCCInfoResponse>(_RemoveCCInfoResponse_QNAME, RemoveCCInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenTransID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "genTransID")
    public JAXBElement<GenTransID> createGenTransID(GenTransID value) {
        return new JAXBElement<GenTransID>(_GenTransID_QNAME, GenTransID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCInfo")
    public JAXBElement<CreateCCInfo> createCreateCCInfo(CreateCCInfo value) {
        return new JAXBElement<CreateCCInfo>(_CreateCCInfo_QNAME, CreateCCInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetCCDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "resetCCDB")
    public JAXBElement<ResetCCDB> createResetCCDB(ResetCCDB value) {
        return new JAXBElement<ResetCCDB>(_ResetCCDB_QNAME, ResetCCDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoCredit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "doCredit")
    public JAXBElement<DoCredit> createDoCredit(DoCredit value) {
        return new JAXBElement<DoCredit>(_DoCredit_QNAME, DoCredit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveCCAuthInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "removeCCAuthInfo")
    public JAXBElement<RemoveCCAuthInfo> createRemoveCCAuthInfo(RemoveCCAuthInfo value) {
        return new JAXBElement<RemoveCCAuthInfo>(_RemoveCCAuthInfo_QNAME, RemoveCCAuthInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountForGSResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createAccountForGSResponse")
    public JAXBElement<CreateAccountForGSResponse> createCreateAccountForGSResponse(CreateAccountForGSResponse value) {
        return new JAXBElement<CreateAccountForGSResponse>(_CreateAccountForGSResponse_QNAME, CreateAccountForGSResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenCCNumResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "genCCNumResponse")
    public JAXBElement<GenCCNumResponse> createGenCCNumResponse(GenCCNumResponse value) {
        return new JAXBElement<GenCCNumResponse>(_GenCCNumResponse_QNAME, GenCCNumResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCOwnerInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCOwnerInfoResponse")
    public JAXBElement<CreateCCOwnerInfoResponse> createCreateCCOwnerInfoResponse(CreateCCOwnerInfoResponse value) {
        return new JAXBElement<CreateCCOwnerInfoResponse>(_CreateCCOwnerInfoResponse_QNAME, CreateCCOwnerInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCAuthInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCAuthInfoResponse")
    public JAXBElement<CreateCCAuthInfoResponse> createCreateCCAuthInfoResponse(CreateCCAuthInfoResponse value) {
        return new JAXBElement<CreateCCAuthInfoResponse>(_CreateCCAuthInfoResponse_QNAME, CreateCCAuthInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearCCDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "clearCCDBResponse")
    public JAXBElement<ClearCCDBResponse> createClearCCDBResponse(ClearCCDBResponse value) {
        return new JAXBElement<ClearCCDBResponse>(_ClearCCDBResponse_QNAME, ClearCCDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCCInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "updateCCInfo")
    public JAXBElement<UpdateCCInfo> createUpdateCCInfo(UpdateCCInfo value) {
        return new JAXBElement<UpdateCCInfo>(_UpdateCCInfo_QNAME, UpdateCCInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoCreditResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "doCreditResponse")
    public JAXBElement<DoCreditResponse> createDoCreditResponse(DoCreditResponse value) {
        return new JAXBElement<DoCreditResponse>(_DoCreditResponse_QNAME, DoCreditResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCCAuthInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "updateCCAuthInfo")
    public JAXBElement<UpdateCCAuthInfo> createUpdateCCAuthInfo(UpdateCCAuthInfo value) {
        return new JAXBElement<UpdateCCAuthInfo>(_UpdateCCAuthInfo_QNAME, UpdateCCAuthInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCCOwnerInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "updateCCOwnerInfoResponse")
    public JAXBElement<UpdateCCOwnerInfoResponse> createUpdateCCOwnerInfoResponse(UpdateCCOwnerInfoResponse value) {
        return new JAXBElement<UpdateCCOwnerInfoResponse>(_UpdateCCOwnerInfoResponse_QNAME, UpdateCCOwnerInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearCCDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "clearCCDB")
    public JAXBElement<ClearCCDB> createClearCCDB(ClearCCDB value) {
        return new JAXBElement<ClearCCDB>(_ClearCCDB_QNAME, ClearCCDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenTransIDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "genTransIDResponse")
    public JAXBElement<GenTransIDResponse> createGenTransIDResponse(GenTransIDResponse value) {
        return new JAXBElement<GenTransIDResponse>(_GenTransIDResponse_QNAME, GenTransIDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoDebit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "doDebit")
    public JAXBElement<DoDebit> createDoDebit(DoDebit value) {
        return new JAXBElement<DoDebit>(_DoDebit_QNAME, DoDebit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoDebitResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "doDebitResponse")
    public JAXBElement<DoDebitResponse> createDoDebitResponse(DoDebitResponse value) {
        return new JAXBElement<DoDebitResponse>(_DoDebitResponse_QNAME, DoDebitResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowHistoryInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "showHistoryInfoResponse")
    public JAXBElement<ShowHistoryInfoResponse> createShowHistoryInfoResponse(ShowHistoryInfoResponse value) {
        return new JAXBElement<ShowHistoryInfoResponse>(_ShowHistoryInfoResponse_QNAME, ShowHistoryInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenCCNum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "genCCNum")
    public JAXBElement<GenCCNum> createGenCCNum(GenCCNum value) {
        return new JAXBElement<GenCCNum>(_GenCCNum_QNAME, GenCCNum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCCInfoWrapperResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "getCCInfoWrapperResponse")
    public JAXBElement<GetCCInfoWrapperResponse> createGetCCInfoWrapperResponse(GetCCInfoWrapperResponse value) {
        return new JAXBElement<GetCCInfoWrapperResponse>(_GetCCInfoWrapperResponse_QNAME, GetCCInfoWrapperResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetCCDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "resetCCDBResponse")
    public JAXBElement<ResetCCDBResponse> createResetCCDBResponse(ResetCCDBResponse value) {
        return new JAXBElement<ResetCCDBResponse>(_ResetCCDBResponse_QNAME, ResetCCDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "validateCard")
    public JAXBElement<ValidateCard> createValidateCard(ValidateCard value) {
        return new JAXBElement<ValidateCard>(_ValidateCard_QNAME, ValidateCard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowHistoryInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "showHistoryInfo")
    public JAXBElement<ShowHistoryInfo> createShowHistoryInfo(ShowHistoryInfo value) {
        return new JAXBElement<ShowHistoryInfo>(_ShowHistoryInfo_QNAME, ShowHistoryInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateCardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "validateCardResponse")
    public JAXBElement<ValidateCardResponse> createValidateCardResponse(ValidateCardResponse value) {
        return new JAXBElement<ValidateCardResponse>(_ValidateCardResponse_QNAME, ValidateCardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCCInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "updateCCInfoResponse")
    public JAXBElement<UpdateCCInfoResponse> createUpdateCCInfoResponse(UpdateCCInfoResponse value) {
        return new JAXBElement<UpdateCCInfoResponse>(_UpdateCCInfoResponse_QNAME, UpdateCCInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveCCAuthInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "removeCCAuthInfoResponse")
    public JAXBElement<RemoveCCAuthInfoResponse> createRemoveCCAuthInfoResponse(RemoveCCAuthInfoResponse value) {
        return new JAXBElement<RemoveCCAuthInfoResponse>(_RemoveCCAuthInfoResponse_QNAME, RemoveCCAuthInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveCCInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "removeCCInfo")
    public JAXBElement<RemoveCCInfo> createRemoveCCInfo(RemoveCCInfo value) {
        return new JAXBElement<RemoveCCInfo>(_RemoveCCInfo_QNAME, RemoveCCInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCAuthInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCAuthInfo")
    public JAXBElement<CreateCCAuthInfo> createCreateCCAuthInfo(CreateCCAuthInfo value) {
        return new JAXBElement<CreateCCAuthInfo>(_CreateCCAuthInfo_QNAME, CreateCCAuthInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveCCOwner }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "removeCCOwner")
    public JAXBElement<RemoveCCOwner> createRemoveCCOwner(RemoveCCOwner value) {
        return new JAXBElement<RemoveCCOwner>(_RemoveCCOwner_QNAME, RemoveCCOwner.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveCCOwnerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "removeCCOwnerResponse")
    public JAXBElement<RemoveCCOwnerResponse> createRemoveCCOwnerResponse(RemoveCCOwnerResponse value) {
        return new JAXBElement<RemoveCCOwnerResponse>(_RemoveCCOwnerResponse_QNAME, RemoveCCOwnerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCOwnerInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCOwnerInfo")
    public JAXBElement<CreateCCOwnerInfo> createCreateCCOwnerInfo(CreateCCOwnerInfo value) {
        return new JAXBElement<CreateCCOwnerInfo>(_CreateCCOwnerInfo_QNAME, CreateCCOwnerInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCInfoResponse")
    public JAXBElement<CreateCCInfoResponse> createCreateCCInfoResponse(CreateCCInfoResponse value) {
        return new JAXBElement<CreateCCInfoResponse>(_CreateCCInfoResponse_QNAME, CreateCCInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCCOwnerInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "updateCCOwnerInfo")
    public JAXBElement<UpdateCCOwnerInfo> createUpdateCCOwnerInfo(UpdateCCOwnerInfo value) {
        return new JAXBElement<UpdateCCOwnerInfo>(_UpdateCCOwnerInfo_QNAME, UpdateCCOwnerInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateNewCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createNewCustomer")
    public JAXBElement<CreateNewCustomer> createCreateNewCustomer(CreateNewCustomer value) {
        return new JAXBElement<CreateNewCustomer>(_CreateNewCustomer_QNAME, CreateNewCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateNewCustomerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createNewCustomerResponse")
    public JAXBElement<CreateNewCustomerResponse> createCreateNewCustomerResponse(CreateNewCustomerResponse value) {
        return new JAXBElement<CreateNewCustomerResponse>(_CreateNewCustomerResponse_QNAME, CreateNewCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCCInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "getCCInfoResponse")
    public JAXBElement<GetCCInfoResponse> createGetCCInfoResponse(GetCCInfoResponse value) {
        return new JAXBElement<GetCCInfoResponse>(_GetCCInfoResponse_QNAME, GetCCInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCCInfoWrapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "getCCInfoWrapper")
    public JAXBElement<GetCCInfoWrapper> createGetCCInfoWrapper(GetCCInfoWrapper value) {
        return new JAXBElement<GetCCInfoWrapper>(_GetCCInfoWrapper_QNAME, GetCCInfoWrapper.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCCInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "getCCInfo")
    public JAXBElement<GetCCInfo> createGetCCInfo(GetCCInfo value) {
        return new JAXBElement<GetCCInfo>(_GetCCInfo_QNAME, GetCCInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCCAuthInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "updateCCAuthInfoResponse")
    public JAXBElement<UpdateCCAuthInfoResponse> createUpdateCCAuthInfoResponse(UpdateCCAuthInfoResponse value) {
        return new JAXBElement<UpdateCCAuthInfoResponse>(_UpdateCCAuthInfoResponse_QNAME, UpdateCCAuthInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCHistoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCHistoryResponse")
    public JAXBElement<CreateCCHistoryResponse> createCreateCCHistoryResponse(CreateCCHistoryResponse value) {
        return new JAXBElement<CreateCCHistoryResponse>(_CreateCCHistoryResponse_QNAME, CreateCCHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCCHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createCCHistory")
    public JAXBElement<CreateCCHistory> createCreateCCHistory(CreateCCHistory value) {
        return new JAXBElement<CreateCCHistory>(_CreateCCHistory_QNAME, CreateCCHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAccountForGS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.ccdb.gs.svt.websphere.ibm.com/", name = "createAccountForGS")
    public JAXBElement<CreateAccountForGS> createCreateAccountForGS(CreateAccountForGS value) {
        return new JAXBElement<CreateAccountForGS>(_CreateAccountForGS_QNAME, CreateAccountForGS.class, null, value);
    }

}
