//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.gsdb.jaxws.client;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for customerWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customerWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="custPwd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numInvoicesCompleted" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numInvoicesCreated" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customerWrapper", propOrder = {
    "custID",
    "custName",
    "custPwd",
    "numInvoicesCompleted",
    "numInvoicesCreated"
})
public class CustomerWrapper implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = -6130490299049705807L;
	protected String custID;
    protected String custName;
    protected String custPwd;
    protected int numInvoicesCompleted;
    protected int numInvoicesCreated;

    /**
     * Gets the value of the custID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustID() {
        return custID;
    }

    /**
     * Sets the value of the custID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustID(String value) {
        this.custID = value;
    }

    /**
     * Gets the value of the custName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustName() {
        return custName;
    }

    /**
     * Sets the value of the custName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustName(String value) {
        this.custName = value;
    }

    /**
     * Gets the value of the custPwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustPwd() {
        return custPwd;
    }

    /**
     * Sets the value of the custPwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustPwd(String value) {
        this.custPwd = value;
    }

    /**
     * Gets the value of the numInvoicesCompleted property.
     * 
     */
    public int getNumInvoicesCompleted() {
        return numInvoicesCompleted;
    }

    /**
     * Sets the value of the numInvoicesCompleted property.
     * 
     */
    public void setNumInvoicesCompleted(int value) {
        this.numInvoicesCompleted = value;
    }

    /**
     * Gets the value of the numInvoicesCreated property.
     * 
     */
    public int getNumInvoicesCreated() {
        return numInvoicesCreated;
    }

    /**
     * Sets the value of the numInvoicesCreated property.
     * 
     */
    public void setNumInvoicesCreated(int value) {
        this.numInvoicesCreated = value;
    }

}
