//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.gsdb.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "GarageSaleStoreManagerLocal", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GarageSaleStoreManagerLocal {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkOut", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.CheckOut")
    @ResponseWrapper(localName = "checkOutResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.CheckOutResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/checkOutRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/checkOutResponse")
    public boolean checkOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<CartItem> arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "orderShipped", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.OrderShipped")
    @ResponseWrapper(localName = "orderShippedResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.OrderShippedResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/orderShippedRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/orderShippedResponse")
    public void orderShipped(
        @WebParam(name = "arg0", targetNamespace = "")
        PaymentInfoWrapper arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<CartItem> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        CustomerInfoWrapper arg2);

    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.CategoryWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCategories", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListCategories")
    @ResponseWrapper(localName = "listCategoriesResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListCategoriesResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listCategoriesRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listCategoriesResponse")
    public List<CategoryWrapper> listCategories();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.MfgCategoryWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMfgCategories", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListMfgCategories")
    @ResponseWrapper(localName = "listMfgCategoriesResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListMfgCategoriesResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listMfgCategoriesRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listMfgCategoriesResponse")
    public List<MfgCategoryWrapper> listMfgCategories(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.MfgCategoryWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllMfgCategories", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListAllMfgCategories")
    @ResponseWrapper(localName = "listAllMfgCategoriesResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListAllMfgCategoriesResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listAllMfgCategoriesRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listAllMfgCategoriesResponse")
    public List<MfgCategoryWrapper> listAllMfgCategories();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.InventoryWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInventory", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListInventory")
    @ResponseWrapper(localName = "listInventoryResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListInventoryResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listInventoryRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listInventoryResponse")
    public List<InventoryWrapper> listInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.InventoryWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listInventoryByCategoryOrMfg", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListInventoryByCategoryOrMfg")
    @ResponseWrapper(localName = "listInventoryByCategoryOrMfgResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListInventoryByCategoryOrMfgResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listInventoryByCategoryOrMfgRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listInventoryByCategoryOrMfgResponse")
    public List<InventoryWrapper> listInventoryByCategoryOrMfg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.InventoryWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllInventory", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListAllInventory")
    @ResponseWrapper(localName = "listAllInventoryResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListAllInventoryResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listAllInventoryRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listAllInventoryResponse")
    public List<InventoryWrapper> listAllInventory();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllCustomers", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListAllCustomers")
    @ResponseWrapper(localName = "listAllCustomersResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ListAllCustomersResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listAllCustomersRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/listAllCustomersResponse")
    public List<Object> listAllCustomers();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalStoreCredit", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetTotalStoreCredit")
    @ResponseWrapper(localName = "getTotalStoreCreditResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetTotalStoreCreditResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getTotalStoreCreditRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getTotalStoreCreditResponse")
    public String getTotalStoreCredit();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.websphere.svt.gs.gsdb.jaxws.client.InventoryWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInventory", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetInventory")
    @ResponseWrapper(localName = "getInventoryResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetInventoryResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getInventoryRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getInventoryResponse")
    public InventoryWrapper getInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.websphere.svt.gs.gsdb.jaxws.client.CategoryWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategory", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCategory")
    @ResponseWrapper(localName = "getCategoryResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCategoryResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCategoryRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCategoryResponse")
    public CategoryWrapper getCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.websphere.svt.gs.gsdb.jaxws.client.CustomerInfoWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerInfo", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCustomerInfo")
    @ResponseWrapper(localName = "getCustomerInfoResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCustomerInfoResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCustomerInfoRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCustomerInfoResponse")
    public CustomerInfoWrapper getCustomerInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ibm.websphere.svt.gs.gsdb.jaxws.client.CustomerWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCustomer")
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCustomerResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCustomerRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCustomerResponse")
    public CustomerWrapper getCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "populateInventory", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateInventory")
    @ResponseWrapper(localName = "populateInventoryResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateInventoryResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateInventoryRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateInventoryResponse")
    public boolean populateInventory(
        @WebParam(name = "arg0", targetNamespace = "")
        SettingsWrapper arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "populateCustomers", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateCustomers")
    @ResponseWrapper(localName = "populateCustomersResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateCustomersResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateCustomersRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateCustomersResponse")
    public boolean populateCustomers(
        @WebParam(name = "arg0", targetNamespace = "")
        SettingsWrapper arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<CCInfoWrapper> arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "populateBankDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateBankDB")
    @ResponseWrapper(localName = "populateBankDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateBankDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateBankDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateBankDBResponse")
    public void populateBankDB(
        @WebParam(name = "arg0", targetNamespace = "")
        SettingsWrapper arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.websphere.svt.gs.gsdb.jaxws.client.CCInfoWrapper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "populateCCDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateCCDB")
    @ResponseWrapper(localName = "populateCCDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.PopulateCCDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateCCDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/populateCCDBResponse")
    public List<CCInfoWrapper> populateCCDB(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearGSDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ClearGSDB")
    @ResponseWrapper(localName = "clearGSDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ClearGSDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/clearGSDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/clearGSDBResponse")
    public boolean clearGSDB();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetGSDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ResetGSDB")
    @ResponseWrapper(localName = "resetGSDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ResetGSDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/resetGSDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/resetGSDBResponse")
    public boolean resetGSDB(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearBankDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ClearBankDB")
    @ResponseWrapper(localName = "clearBankDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ClearBankDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/clearBankDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/clearBankDBResponse")
    public boolean clearBankDB();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetBankDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ResetBankDB")
    @ResponseWrapper(localName = "resetBankDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ResetBankDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/resetBankDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/resetBankDBResponse")
    public boolean resetBankDB();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearCCDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ClearCCDB")
    @ResponseWrapper(localName = "clearCCDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ClearCCDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/clearCCDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/clearCCDBResponse")
    public boolean clearCCDB();

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resetCCDB", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ResetCCDB")
    @ResponseWrapper(localName = "resetCCDBResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.ResetCCDBResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/resetCCDBRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/resetCCDBResponse")
    public boolean resetCCDB();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCCHistoryData", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCCHistoryData")
    @ResponseWrapper(localName = "getCCHistoryDataResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetCCHistoryDataResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCCHistoryDataRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getCCHistoryDataResponse")
    public String getCCHistoryData();

    /**
     * 
     * @return
     *     returns com.ibm.websphere.svt.gs.gsdb.jaxws.client.SettingsWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSettings", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetSettings")
    @ResponseWrapper(localName = "getSettingsResponse", targetNamespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", className = "com.ibm.websphere.svt.gs.gsdb.jaxws.client.GetSettingsResponse")
    @Action(input = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getSettingsRequest", output = "http://view.session.gsdb.gs.svt.websphere.ibm.com/GarageSaleStoreManagerLocal/getSettingsResponse")
    public SettingsWrapper getSettings();

}
