//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.gsdb.jaxws.client;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.websphere.svt.gs.gsdb.jaxws.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClearCCDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "clearCCDBResponse");
    private final static QName _PopulateBankDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateBankDB");
    private final static QName _PopulateInventory_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateInventory");
    private final static QName _PopulateCCDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateCCDBResponse");
    private final static QName _ClearGSDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "clearGSDB");
    private final static QName _GetCCHistoryData_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCCHistoryData");
    private final static QName _GetCategory_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCategory");
    private final static QName _ClearCCDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "clearCCDB");
    private final static QName _ResetGSDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "resetGSDBResponse");
    private final static QName _OrderShipped_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "orderShipped");
    private final static QName _GetInventoryResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getInventoryResponse");
    private final static QName _ClearBankDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "clearBankDB");
    private final static QName _ResetCCDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "resetCCDB");
    private final static QName _PopulateCustomers_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateCustomers");
    private final static QName _GetSettings_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getSettings");
    private final static QName _ListAllInventoryResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listAllInventoryResponse");
    private final static QName _PopulateInventoryResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateInventoryResponse");
    private final static QName _ListAllMfgCategories_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listAllMfgCategories");
    private final static QName _ListAllCustomersResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listAllCustomersResponse");
    private final static QName _GetCustomerInfo_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCustomerInfo");
    private final static QName _ListCategories_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listCategories");
    private final static QName _ListMfgCategories_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listMfgCategories");
    private final static QName _CheckOut_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "checkOut");
    private final static QName _OrderShippedResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "orderShippedResponse");
    private final static QName _CheckOutResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "checkOutResponse");
    private final static QName _ResetBankDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "resetBankDB");
    private final static QName _ListInventoryResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listInventoryResponse");
    private final static QName _GetInventory_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getInventory");
    private final static QName _ListCategoriesResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listCategoriesResponse");
    private final static QName _GetCustomerResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCustomerResponse");
    private final static QName _GetCategoryResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCategoryResponse");
    private final static QName _ListAllCustomers_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listAllCustomers");
    private final static QName _GetSettingsResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getSettingsResponse");
    private final static QName _PopulateBankDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateBankDBResponse");
    private final static QName _ListInventoryByCategoryOrMfg_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listInventoryByCategoryOrMfg");
    private final static QName _ListInventoryByCategoryOrMfgResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listInventoryByCategoryOrMfgResponse");
    private final static QName _ResetBankDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "resetBankDBResponse");
    private final static QName _GetCCHistoryDataResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCCHistoryDataResponse");
    private final static QName _GetCustomer_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCustomer");
    private final static QName _PopulateCustomersResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateCustomersResponse");
    private final static QName _ListAllInventory_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listAllInventory");
    private final static QName _GetCustomerInfoResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getCustomerInfoResponse");
    private final static QName _ClearBankDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "clearBankDBResponse");
    private final static QName _ListMfgCategoriesResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listMfgCategoriesResponse");
    private final static QName _ListInventory_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listInventory");
    private final static QName _ResetGSDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "resetGSDB");
    private final static QName _GetTotalStoreCredit_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getTotalStoreCredit");
    private final static QName _ListAllMfgCategoriesResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "listAllMfgCategoriesResponse");
    private final static QName _PopulateCCDB_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "populateCCDB");
    private final static QName _ClearGSDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "clearGSDBResponse");
    private final static QName _GetTotalStoreCreditResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "getTotalStoreCreditResponse");
    private final static QName _ResetCCDBResponse_QNAME = new QName("http://view.session.gsdb.gs.svt.websphere.ibm.com/", "resetCCDBResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.websphere.svt.gs.gsdb.jaxws.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CCInfoWrapper }
     * 
     */
    public CCInfoWrapper createCCInfoWrapper() {
        return new CCInfoWrapper();
    }

    /**
     * Create an instance of {@link PopulateBankDBResponse }
     * 
     */
    public PopulateBankDBResponse createPopulateBankDBResponse() {
        return new PopulateBankDBResponse();
    }

    /**
     * Create an instance of {@link ClearGSDB }
     * 
     */
    public ClearGSDB createClearGSDB() {
        return new ClearGSDB();
    }

    /**
     * Create an instance of {@link ClearCCDB }
     * 
     */
    public ClearCCDB createClearCCDB() {
        return new ClearCCDB();
    }

    /**
     * Create an instance of {@link GetCCHistoryDataResponse }
     * 
     */
    public GetCCHistoryDataResponse createGetCCHistoryDataResponse() {
        return new GetCCHistoryDataResponse();
    }

    /**
     * Create an instance of {@link ListCategoriesResponse }
     * 
     */
    public ListCategoriesResponse createListCategoriesResponse() {
        return new ListCategoriesResponse();
    }

    /**
     * Create an instance of {@link PopulateBankDB }
     * 
     */
    public PopulateBankDB createPopulateBankDB() {
        return new PopulateBankDB();
    }

    /**
     * Create an instance of {@link ListAllCustomersResponse }
     * 
     */
    public ListAllCustomersResponse createListAllCustomersResponse() {
        return new ListAllCustomersResponse();
    }

    /**
     * Create an instance of {@link GetSettings }
     * 
     */
    public GetSettings createGetSettings() {
        return new GetSettings();
    }

    /**
     * Create an instance of {@link ClearGSDBResponse }
     * 
     */
    public ClearGSDBResponse createClearGSDBResponse() {
        return new ClearGSDBResponse();
    }

    /**
     * Create an instance of {@link OrderShippedResponse }
     * 
     */
    public OrderShippedResponse createOrderShippedResponse() {
        return new OrderShippedResponse();
    }

    /**
     * Create an instance of {@link ListMfgCategories }
     * 
     */
    public ListMfgCategories createListMfgCategories() {
        return new ListMfgCategories();
    }

    /**
     * Create an instance of {@link ResetCCDB }
     * 
     */
    public ResetCCDB createResetCCDB() {
        return new ResetCCDB();
    }

    /**
     * Create an instance of {@link GetInventory }
     * 
     */
    public GetInventory createGetInventory() {
        return new GetInventory();
    }

    /**
     * Create an instance of {@link ListInventoryByCategoryOrMfg }
     * 
     */
    public ListInventoryByCategoryOrMfg createListInventoryByCategoryOrMfg() {
        return new ListInventoryByCategoryOrMfg();
    }

    /**
     * Create an instance of {@link ListAllMfgCategories }
     * 
     */
    public ListAllMfgCategories createListAllMfgCategories() {
        return new ListAllMfgCategories();
    }

    /**
     * Create an instance of {@link GetTotalStoreCreditResponse }
     * 
     */
    public GetTotalStoreCreditResponse createGetTotalStoreCreditResponse() {
        return new GetTotalStoreCreditResponse();
    }

    /**
     * Create an instance of {@link PopulateCCDB }
     * 
     */
    public PopulateCCDB createPopulateCCDB() {
        return new PopulateCCDB();
    }

    /**
     * Create an instance of {@link ResetGSDBResponse }
     * 
     */
    public ResetGSDBResponse createResetGSDBResponse() {
        return new ResetGSDBResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfo }
     * 
     */
    public GetCustomerInfo createGetCustomerInfo() {
        return new GetCustomerInfo();
    }

    /**
     * Create an instance of {@link PopulateInventory }
     * 
     */
    public PopulateInventory createPopulateInventory() {
        return new PopulateInventory();
    }

    /**
     * Create an instance of {@link ListAllInventory }
     * 
     */
    public ListAllInventory createListAllInventory() {
        return new ListAllInventory();
    }

    /**
     * Create an instance of {@link GetInventoryResponse }
     * 
     */
    public GetInventoryResponse createGetInventoryResponse() {
        return new GetInventoryResponse();
    }

    /**
     * Create an instance of {@link ListInventoryResponse }
     * 
     */
    public ListInventoryResponse createListInventoryResponse() {
        return new ListInventoryResponse();
    }

    /**
     * Create an instance of {@link GetCustomer }
     * 
     */
    public GetCustomer createGetCustomer() {
        return new GetCustomer();
    }

    /**
     * Create an instance of {@link ListMfgCategoriesResponse }
     * 
     */
    public ListMfgCategoriesResponse createListMfgCategoriesResponse() {
        return new ListMfgCategoriesResponse();
    }

    /**
     * Create an instance of {@link ClearBankDB }
     * 
     */
    public ClearBankDB createClearBankDB() {
        return new ClearBankDB();
    }

    /**
     * Create an instance of {@link PopulateCustomersResponse }
     * 
     */
    public PopulateCustomersResponse createPopulateCustomersResponse() {
        return new PopulateCustomersResponse();
    }

    /**
     * Create an instance of {@link GetCCHistoryData }
     * 
     */
    public GetCCHistoryData createGetCCHistoryData() {
        return new GetCCHistoryData();
    }

    /**
     * Create an instance of {@link GetCustomerResponse }
     * 
     */
    public GetCustomerResponse createGetCustomerResponse() {
        return new GetCustomerResponse();
    }

    /**
     * Create an instance of {@link ResetBankDB }
     * 
     */
    public ResetBankDB createResetBankDB() {
        return new ResetBankDB();
    }

    /**
     * Create an instance of {@link ListCategories }
     * 
     */
    public ListCategories createListCategories() {
        return new ListCategories();
    }

    /**
     * Create an instance of {@link ListInventory }
     * 
     */
    public ListInventory createListInventory() {
        return new ListInventory();
    }

    /**
     * Create an instance of {@link ListInventoryByCategoryOrMfgResponse }
     * 
     */
    public ListInventoryByCategoryOrMfgResponse createListInventoryByCategoryOrMfgResponse() {
        return new ListInventoryByCategoryOrMfgResponse();
    }

    /**
     * Create an instance of {@link PopulateCustomers }
     * 
     */
    public PopulateCustomers createPopulateCustomers() {
        return new PopulateCustomers();
    }

    /**
     * Create an instance of {@link GetCategoryResponse }
     * 
     */
    public GetCategoryResponse createGetCategoryResponse() {
        return new GetCategoryResponse();
    }

    /**
     * Create an instance of {@link ClearCCDBResponse }
     * 
     */
    public ClearCCDBResponse createClearCCDBResponse() {
        return new ClearCCDBResponse();
    }

    /**
     * Create an instance of {@link ListAllInventoryResponse }
     * 
     */
    public ListAllInventoryResponse createListAllInventoryResponse() {
        return new ListAllInventoryResponse();
    }

    /**
     * Create an instance of {@link ResetBankDBResponse }
     * 
     */
    public ResetBankDBResponse createResetBankDBResponse() {
        return new ResetBankDBResponse();
    }

    /**
     * Create an instance of {@link ListAllCustomers }
     * 
     */
    public ListAllCustomers createListAllCustomers() {
        return new ListAllCustomers();
    }

    /**
     * Create an instance of {@link ResetGSDB }
     * 
     */
    public ResetGSDB createResetGSDB() {
        return new ResetGSDB();
    }

    /**
     * Create an instance of {@link ResetCCDBResponse }
     * 
     */
    public ResetCCDBResponse createResetCCDBResponse() {
        return new ResetCCDBResponse();
    }

    /**
     * Create an instance of {@link GetTotalStoreCredit }
     * 
     */
    public GetTotalStoreCredit createGetTotalStoreCredit() {
        return new GetTotalStoreCredit();
    }

    /**
     * Create an instance of {@link CheckOutResponse }
     * 
     */
    public CheckOutResponse createCheckOutResponse() {
        return new CheckOutResponse();
    }

    /**
     * Create an instance of {@link PopulateInventoryResponse }
     * 
     */
    public PopulateInventoryResponse createPopulateInventoryResponse() {
        return new PopulateInventoryResponse();
    }

    /**
     * Create an instance of {@link CheckOut }
     * 
     */
    public CheckOut createCheckOut() {
        return new CheckOut();
    }

    /**
     * Create an instance of {@link GetCategory }
     * 
     */
    public GetCategory createGetCategory() {
        return new GetCategory();
    }

    /**
     * Create an instance of {@link ListAllMfgCategoriesResponse }
     * 
     */
    public ListAllMfgCategoriesResponse createListAllMfgCategoriesResponse() {
        return new ListAllMfgCategoriesResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfoResponse }
     * 
     */
    public GetCustomerInfoResponse createGetCustomerInfoResponse() {
        return new GetCustomerInfoResponse();
    }

    /**
     * Create an instance of {@link ClearBankDBResponse }
     * 
     */
    public ClearBankDBResponse createClearBankDBResponse() {
        return new ClearBankDBResponse();
    }

    /**
     * Create an instance of {@link PopulateCCDBResponse }
     * 
     */
    public PopulateCCDBResponse createPopulateCCDBResponse() {
        return new PopulateCCDBResponse();
    }

    /**
     * Create an instance of {@link OrderShipped }
     * 
     */
    public OrderShipped createOrderShipped() {
        return new OrderShipped();
    }

    /**
     * Create an instance of {@link GetSettingsResponse }
     * 
     */
    public GetSettingsResponse createGetSettingsResponse() {
        return new GetSettingsResponse();
    }

    /**
     * Create an instance of {@link PaymentInfoWrapper }
     * 
     */
    public PaymentInfoWrapper createPaymentInfoWrapper() {
        return new PaymentInfoWrapper();
    }

    /**
     * Create an instance of {@link CategoryWrapper }
     * 
     */
    public CategoryWrapper createCategoryWrapper() {
        return new CategoryWrapper();
    }

    /**
     * Create an instance of {@link InventoryWrapper }
     * 
     */
    public InventoryWrapper createInventoryWrapper() {
        return new InventoryWrapper();
    }

    /**
     * Create an instance of {@link CustomerInfoWrapper }
     * 
     */
    public CustomerInfoWrapper createCustomerInfoWrapper() {
        return new CustomerInfoWrapper();
    }

    /**
     * Create an instance of {@link MfgCategoryWrapper }
     * 
     */
    public MfgCategoryWrapper createMfgCategoryWrapper() {
        return new MfgCategoryWrapper();
    }

    /**
     * Create an instance of {@link CustomerWrapper }
     * 
     */
    public CustomerWrapper createCustomerWrapper() {
        return new CustomerWrapper();
    }

    /**
     * Create an instance of {@link SettingsWrapper }
     * 
     */
    public SettingsWrapper createSettingsWrapper() {
        return new SettingsWrapper();
    }

    /**
     * Create an instance of {@link CartItem }
     * 
     */
    public CartItem createCartItem() {
        return new CartItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearCCDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "clearCCDBResponse")
    public JAXBElement<ClearCCDBResponse> createClearCCDBResponse(ClearCCDBResponse value) {
        return new JAXBElement<ClearCCDBResponse>(_ClearCCDBResponse_QNAME, ClearCCDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateBankDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateBankDB")
    public JAXBElement<PopulateBankDB> createPopulateBankDB(PopulateBankDB value) {
        return new JAXBElement<PopulateBankDB>(_PopulateBankDB_QNAME, PopulateBankDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateInventory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateInventory")
    public JAXBElement<PopulateInventory> createPopulateInventory(PopulateInventory value) {
        return new JAXBElement<PopulateInventory>(_PopulateInventory_QNAME, PopulateInventory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateCCDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateCCDBResponse")
    public JAXBElement<PopulateCCDBResponse> createPopulateCCDBResponse(PopulateCCDBResponse value) {
        return new JAXBElement<PopulateCCDBResponse>(_PopulateCCDBResponse_QNAME, PopulateCCDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearGSDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "clearGSDB")
    public JAXBElement<ClearGSDB> createClearGSDB(ClearGSDB value) {
        return new JAXBElement<ClearGSDB>(_ClearGSDB_QNAME, ClearGSDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCCHistoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCCHistoryData")
    public JAXBElement<GetCCHistoryData> createGetCCHistoryData(GetCCHistoryData value) {
        return new JAXBElement<GetCCHistoryData>(_GetCCHistoryData_QNAME, GetCCHistoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCategory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCategory")
    public JAXBElement<GetCategory> createGetCategory(GetCategory value) {
        return new JAXBElement<GetCategory>(_GetCategory_QNAME, GetCategory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearCCDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "clearCCDB")
    public JAXBElement<ClearCCDB> createClearCCDB(ClearCCDB value) {
        return new JAXBElement<ClearCCDB>(_ClearCCDB_QNAME, ClearCCDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetGSDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "resetGSDBResponse")
    public JAXBElement<ResetGSDBResponse> createResetGSDBResponse(ResetGSDBResponse value) {
        return new JAXBElement<ResetGSDBResponse>(_ResetGSDBResponse_QNAME, ResetGSDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderShipped }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "orderShipped")
    public JAXBElement<OrderShipped> createOrderShipped(OrderShipped value) {
        return new JAXBElement<OrderShipped>(_OrderShipped_QNAME, OrderShipped.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInventoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getInventoryResponse")
    public JAXBElement<GetInventoryResponse> createGetInventoryResponse(GetInventoryResponse value) {
        return new JAXBElement<GetInventoryResponse>(_GetInventoryResponse_QNAME, GetInventoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearBankDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "clearBankDB")
    public JAXBElement<ClearBankDB> createClearBankDB(ClearBankDB value) {
        return new JAXBElement<ClearBankDB>(_ClearBankDB_QNAME, ClearBankDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetCCDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "resetCCDB")
    public JAXBElement<ResetCCDB> createResetCCDB(ResetCCDB value) {
        return new JAXBElement<ResetCCDB>(_ResetCCDB_QNAME, ResetCCDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateCustomers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateCustomers")
    public JAXBElement<PopulateCustomers> createPopulateCustomers(PopulateCustomers value) {
        return new JAXBElement<PopulateCustomers>(_PopulateCustomers_QNAME, PopulateCustomers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSettings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getSettings")
    public JAXBElement<GetSettings> createGetSettings(GetSettings value) {
        return new JAXBElement<GetSettings>(_GetSettings_QNAME, GetSettings.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAllInventoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listAllInventoryResponse")
    public JAXBElement<ListAllInventoryResponse> createListAllInventoryResponse(ListAllInventoryResponse value) {
        return new JAXBElement<ListAllInventoryResponse>(_ListAllInventoryResponse_QNAME, ListAllInventoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateInventoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateInventoryResponse")
    public JAXBElement<PopulateInventoryResponse> createPopulateInventoryResponse(PopulateInventoryResponse value) {
        return new JAXBElement<PopulateInventoryResponse>(_PopulateInventoryResponse_QNAME, PopulateInventoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAllMfgCategories }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listAllMfgCategories")
    public JAXBElement<ListAllMfgCategories> createListAllMfgCategories(ListAllMfgCategories value) {
        return new JAXBElement<ListAllMfgCategories>(_ListAllMfgCategories_QNAME, ListAllMfgCategories.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAllCustomersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listAllCustomersResponse")
    public JAXBElement<ListAllCustomersResponse> createListAllCustomersResponse(ListAllCustomersResponse value) {
        return new JAXBElement<ListAllCustomersResponse>(_ListAllCustomersResponse_QNAME, ListAllCustomersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCustomerInfo")
    public JAXBElement<GetCustomerInfo> createGetCustomerInfo(GetCustomerInfo value) {
        return new JAXBElement<GetCustomerInfo>(_GetCustomerInfo_QNAME, GetCustomerInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCategories }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listCategories")
    public JAXBElement<ListCategories> createListCategories(ListCategories value) {
        return new JAXBElement<ListCategories>(_ListCategories_QNAME, ListCategories.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListMfgCategories }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listMfgCategories")
    public JAXBElement<ListMfgCategories> createListMfgCategories(ListMfgCategories value) {
        return new JAXBElement<ListMfgCategories>(_ListMfgCategories_QNAME, ListMfgCategories.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckOut }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "checkOut")
    public JAXBElement<CheckOut> createCheckOut(CheckOut value) {
        return new JAXBElement<CheckOut>(_CheckOut_QNAME, CheckOut.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderShippedResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "orderShippedResponse")
    public JAXBElement<OrderShippedResponse> createOrderShippedResponse(OrderShippedResponse value) {
        return new JAXBElement<OrderShippedResponse>(_OrderShippedResponse_QNAME, OrderShippedResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckOutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "checkOutResponse")
    public JAXBElement<CheckOutResponse> createCheckOutResponse(CheckOutResponse value) {
        return new JAXBElement<CheckOutResponse>(_CheckOutResponse_QNAME, CheckOutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetBankDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "resetBankDB")
    public JAXBElement<ResetBankDB> createResetBankDB(ResetBankDB value) {
        return new JAXBElement<ResetBankDB>(_ResetBankDB_QNAME, ResetBankDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInventoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listInventoryResponse")
    public JAXBElement<ListInventoryResponse> createListInventoryResponse(ListInventoryResponse value) {
        return new JAXBElement<ListInventoryResponse>(_ListInventoryResponse_QNAME, ListInventoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInventory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getInventory")
    public JAXBElement<GetInventory> createGetInventory(GetInventory value) {
        return new JAXBElement<GetInventory>(_GetInventory_QNAME, GetInventory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCategoriesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listCategoriesResponse")
    public JAXBElement<ListCategoriesResponse> createListCategoriesResponse(ListCategoriesResponse value) {
        return new JAXBElement<ListCategoriesResponse>(_ListCategoriesResponse_QNAME, ListCategoriesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCustomerResponse")
    public JAXBElement<GetCustomerResponse> createGetCustomerResponse(GetCustomerResponse value) {
        return new JAXBElement<GetCustomerResponse>(_GetCustomerResponse_QNAME, GetCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCategoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCategoryResponse")
    public JAXBElement<GetCategoryResponse> createGetCategoryResponse(GetCategoryResponse value) {
        return new JAXBElement<GetCategoryResponse>(_GetCategoryResponse_QNAME, GetCategoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAllCustomers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listAllCustomers")
    public JAXBElement<ListAllCustomers> createListAllCustomers(ListAllCustomers value) {
        return new JAXBElement<ListAllCustomers>(_ListAllCustomers_QNAME, ListAllCustomers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSettingsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getSettingsResponse")
    public JAXBElement<GetSettingsResponse> createGetSettingsResponse(GetSettingsResponse value) {
        return new JAXBElement<GetSettingsResponse>(_GetSettingsResponse_QNAME, GetSettingsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateBankDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateBankDBResponse")
    public JAXBElement<PopulateBankDBResponse> createPopulateBankDBResponse(PopulateBankDBResponse value) {
        return new JAXBElement<PopulateBankDBResponse>(_PopulateBankDBResponse_QNAME, PopulateBankDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInventoryByCategoryOrMfg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listInventoryByCategoryOrMfg")
    public JAXBElement<ListInventoryByCategoryOrMfg> createListInventoryByCategoryOrMfg(ListInventoryByCategoryOrMfg value) {
        return new JAXBElement<ListInventoryByCategoryOrMfg>(_ListInventoryByCategoryOrMfg_QNAME, ListInventoryByCategoryOrMfg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInventoryByCategoryOrMfgResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listInventoryByCategoryOrMfgResponse")
    public JAXBElement<ListInventoryByCategoryOrMfgResponse> createListInventoryByCategoryOrMfgResponse(ListInventoryByCategoryOrMfgResponse value) {
        return new JAXBElement<ListInventoryByCategoryOrMfgResponse>(_ListInventoryByCategoryOrMfgResponse_QNAME, ListInventoryByCategoryOrMfgResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetBankDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "resetBankDBResponse")
    public JAXBElement<ResetBankDBResponse> createResetBankDBResponse(ResetBankDBResponse value) {
        return new JAXBElement<ResetBankDBResponse>(_ResetBankDBResponse_QNAME, ResetBankDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCCHistoryDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCCHistoryDataResponse")
    public JAXBElement<GetCCHistoryDataResponse> createGetCCHistoryDataResponse(GetCCHistoryDataResponse value) {
        return new JAXBElement<GetCCHistoryDataResponse>(_GetCCHistoryDataResponse_QNAME, GetCCHistoryDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCustomer")
    public JAXBElement<GetCustomer> createGetCustomer(GetCustomer value) {
        return new JAXBElement<GetCustomer>(_GetCustomer_QNAME, GetCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateCustomersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateCustomersResponse")
    public JAXBElement<PopulateCustomersResponse> createPopulateCustomersResponse(PopulateCustomersResponse value) {
        return new JAXBElement<PopulateCustomersResponse>(_PopulateCustomersResponse_QNAME, PopulateCustomersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAllInventory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listAllInventory")
    public JAXBElement<ListAllInventory> createListAllInventory(ListAllInventory value) {
        return new JAXBElement<ListAllInventory>(_ListAllInventory_QNAME, ListAllInventory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getCustomerInfoResponse")
    public JAXBElement<GetCustomerInfoResponse> createGetCustomerInfoResponse(GetCustomerInfoResponse value) {
        return new JAXBElement<GetCustomerInfoResponse>(_GetCustomerInfoResponse_QNAME, GetCustomerInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearBankDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "clearBankDBResponse")
    public JAXBElement<ClearBankDBResponse> createClearBankDBResponse(ClearBankDBResponse value) {
        return new JAXBElement<ClearBankDBResponse>(_ClearBankDBResponse_QNAME, ClearBankDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListMfgCategoriesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listMfgCategoriesResponse")
    public JAXBElement<ListMfgCategoriesResponse> createListMfgCategoriesResponse(ListMfgCategoriesResponse value) {
        return new JAXBElement<ListMfgCategoriesResponse>(_ListMfgCategoriesResponse_QNAME, ListMfgCategoriesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInventory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listInventory")
    public JAXBElement<ListInventory> createListInventory(ListInventory value) {
        return new JAXBElement<ListInventory>(_ListInventory_QNAME, ListInventory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetGSDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "resetGSDB")
    public JAXBElement<ResetGSDB> createResetGSDB(ResetGSDB value) {
        return new JAXBElement<ResetGSDB>(_ResetGSDB_QNAME, ResetGSDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTotalStoreCredit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getTotalStoreCredit")
    public JAXBElement<GetTotalStoreCredit> createGetTotalStoreCredit(GetTotalStoreCredit value) {
        return new JAXBElement<GetTotalStoreCredit>(_GetTotalStoreCredit_QNAME, GetTotalStoreCredit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListAllMfgCategoriesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "listAllMfgCategoriesResponse")
    public JAXBElement<ListAllMfgCategoriesResponse> createListAllMfgCategoriesResponse(ListAllMfgCategoriesResponse value) {
        return new JAXBElement<ListAllMfgCategoriesResponse>(_ListAllMfgCategoriesResponse_QNAME, ListAllMfgCategoriesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PopulateCCDB }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "populateCCDB")
    public JAXBElement<PopulateCCDB> createPopulateCCDB(PopulateCCDB value) {
        return new JAXBElement<PopulateCCDB>(_PopulateCCDB_QNAME, PopulateCCDB.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClearGSDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "clearGSDBResponse")
    public JAXBElement<ClearGSDBResponse> createClearGSDBResponse(ClearGSDBResponse value) {
        return new JAXBElement<ClearGSDBResponse>(_ClearGSDBResponse_QNAME, ClearGSDBResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTotalStoreCreditResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "getTotalStoreCreditResponse")
    public JAXBElement<GetTotalStoreCreditResponse> createGetTotalStoreCreditResponse(GetTotalStoreCreditResponse value) {
        return new JAXBElement<GetTotalStoreCreditResponse>(_GetTotalStoreCreditResponse_QNAME, GetTotalStoreCreditResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetCCDBResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://view.session.gsdb.gs.svt.websphere.ibm.com/", name = "resetCCDBResponse")
    public JAXBElement<ResetCCDBResponse> createResetCCDBResponse(ResetCCDBResponse value) {
        return new JAXBElement<ResetCCDBResponse>(_ResetCCDBResponse_QNAME, ResetCCDBResponse.class, null, value);
    }

}
