//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.gsdb.jaxws.client;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderShipped complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderShipped">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arg0" type="{http://view.session.gsdb.gs.svt.websphere.ibm.com/}paymentInfoWrapper" minOccurs="0"/>
 *         &lt;element name="arg1" type="{http://cart.gs.svt.websphere.ibm.com}CartItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="arg2" type="{http://view.session.gsdb.gs.svt.websphere.ibm.com/}customerInfoWrapper" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderShipped", propOrder = {
    "arg0",
    "arg1",
    "arg2"
})
public class OrderShipped {

    protected PaymentInfoWrapper arg0;
    protected List<CartItem> arg1;
    protected CustomerInfoWrapper arg2;

    /**
     * Gets the value of the arg0 property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInfoWrapper }
     *     
     */
    public PaymentInfoWrapper getArg0() {
        return arg0;
    }

    /**
     * Sets the value of the arg0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInfoWrapper }
     *     
     */
    public void setArg0(PaymentInfoWrapper value) {
        this.arg0 = value;
    }

    /**
     * Gets the value of the arg1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arg1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArg1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CartItem }
     * 
     * 
     */
    public List<CartItem> getArg1() {
        if (arg1 == null) {
            arg1 = new ArrayList<CartItem>();
        }
        return this.arg1;
    }

    /**
     * Gets the value of the arg2 property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerInfoWrapper }
     *     
     */
    public CustomerInfoWrapper getArg2() {
        return arg2;
    }

    /**
     * Sets the value of the arg2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerInfoWrapper }
     *     
     */
    public void setArg2(CustomerInfoWrapper value) {
        this.arg2 = value;
    }

}
