//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.websphere.svt.gs.gsdb.jaxws.client;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingsWrapper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingsWrapper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numCategories" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numCustomers" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numItemsPerMfg" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numMfgCategories" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numSubAccounts" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="sdoEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wsatEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wsnEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="wsnVariables" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingsWrapper", propOrder = {
    "numCategories",
    "numCustomers",
    "numItemsPerMfg",
    "numMfgCategories",
    "numSubAccounts",
    "sdoEnabled",
    "wsatEnabled",
    "wsnEnabled",
    "wsnVariables"
})
public class SettingsWrapper implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = -5779733543832391854L;
	protected int numCategories;
    protected int numCustomers;
    protected int numItemsPerMfg;
    protected int numMfgCategories;
    protected int numSubAccounts;
    protected boolean sdoEnabled;
    protected boolean wsatEnabled;
    protected boolean wsnEnabled;
    protected String wsnVariables;

    /**
     * Gets the value of the numCategories property.
     * 
     */
    public int getNumCategories() {
        return numCategories;
    }

    /**
     * Sets the value of the numCategories property.
     * 
     */
    public void setNumCategories(int value) {
        this.numCategories = value;
    }

    /**
     * Gets the value of the numCustomers property.
     * 
     */
    public int getNumCustomers() {
        return numCustomers;
    }

    /**
     * Sets the value of the numCustomers property.
     * 
     */
    public void setNumCustomers(int value) {
        this.numCustomers = value;
    }

    /**
     * Gets the value of the numItemsPerMfg property.
     * 
     */
    public int getNumItemsPerMfg() {
        return numItemsPerMfg;
    }

    /**
     * Sets the value of the numItemsPerMfg property.
     * 
     */
    public void setNumItemsPerMfg(int value) {
        this.numItemsPerMfg = value;
    }

    /**
     * Gets the value of the numMfgCategories property.
     * 
     */
    public int getNumMfgCategories() {
        return numMfgCategories;
    }

    /**
     * Sets the value of the numMfgCategories property.
     * 
     */
    public void setNumMfgCategories(int value) {
        this.numMfgCategories = value;
    }

    /**
     * Gets the value of the numSubAccounts property.
     * 
     */
    public int getNumSubAccounts() {
        return numSubAccounts;
    }

    /**
     * Sets the value of the numSubAccounts property.
     * 
     */
    public void setNumSubAccounts(int value) {
        this.numSubAccounts = value;
    }

    /**
     * Gets the value of the sdoEnabled property.
     * 
     */
    public boolean isSdoEnabled() {
        return sdoEnabled;
    }

    /**
     * Sets the value of the sdoEnabled property.
     * 
     */
    public void setSdoEnabled(boolean value) {
        this.sdoEnabled = value;
    }

    /**
     * Gets the value of the wsatEnabled property.
     * 
     */
    public boolean isWsatEnabled() {
        return wsatEnabled;
    }

    /**
     * Sets the value of the wsatEnabled property.
     * 
     */
    public void setWsatEnabled(boolean value) {
        this.wsatEnabled = value;
    }

    /**
     * Gets the value of the wsnEnabled property.
     * 
     */
    public boolean isWsnEnabled() {
        return wsnEnabled;
    }

    /**
     * Sets the value of the wsnEnabled property.
     * 
     */
    public void setWsnEnabled(boolean value) {
        this.wsnEnabled = value;
    }

    /**
     * Gets the value of the wsnVariables property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWsnVariables() {
        return wsnVariables;
    }

    /**
     * Sets the value of the wsnVariables property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWsnVariables(String value) {
        this.wsnVariables = value;
    }

}
